name: SQLite Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run SQLite Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Write targets.txt file
        run: echo "./sqlite3.db" > targets.txt

      - name: Run program
        run: make run ARGS="-f targets.txt -d sqlite3 -t 5s"
